apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.appName }}
  description: ${{ values.description}}   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: ${{ values.name }}
    backstage.io/kubernetes-id: ${{ values.name }} 
    backstage.io/techdocs-ref: dir:.   
  {%- if values.ciType == 'tekton' %} 
    janus-idp.io/tekton: ${{ values.name }} 
  {%- endif %} 
  {%- if values.ciType == 'jenkins' %} 
    jenkins.io/job-full-name: ${{ values.appName }} 
  {%- endif %} 
  {%- if values.ciType == 'githubactions' %} 
    github.com/project-slug: ${{ values.gitRepoSlug }} 
  {%- endif %} 
  {%- if values.ciType == 'gitlabci' %} 
    gitlab.com/project-slug: '${{ values.gitRepoSlug }}'
  {%- endif %}   
spec:
  type: gitops
  owner: ${{ values.owner }} 
  lifecycle: experimental
  dependsOn:
    - component:${{ values.name }}
