kind: Deployment
apiVersion: apps/v1
metadata:
  name: devfile-dotnet-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
  template:
    metadata:
      labels:
        app: devfile-dotnet-deploy
    spec:
      containers:
        - name: main
          image: "dotnet-image:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
