#!/bin/bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" 
ROOT_DIR=$(realpath $SCRIPTDIR/..)

REPO=$1
DIRNAME=$(basename $REPO)
mkdir -p $SCRIPTDIR/samples 
SAMPLE_DIR=$SCRIPTDIR/samples/$DIRNAME 
if [ -d $SAMPLE_DIR ]; then
    (cd $SAMPLE_DIR; git pull 2>&1 > /dev/null)
else 
    (cd $SCRIPTDIR/samples;  git clone $REPO 2>&1 > /dev/null)
fi

APP_NAME=$(yq ".metadata.name" $SAMPLE_DIR/devfile.yaml)
APP_DISPLAY_NAME=$(yq ".metadata.displayName" $SAMPLE_DIR/devfile.yaml)
APP_DESC=$(yq ".metadata.description" $SAMPLE_DIR/devfile.yaml)
APP_TAGS=$(yq ".metadata.tags" $SAMPLE_DIR/devfile.yaml |  yq -o json | yq | tr '[:upper:]' '[:lower:]' | tr -d "\.") 
if [ "$APP_DESC" == "null" ]; then
    APP_DESC="Sample Code for $APP_DISPLAY_NAME"
fi


DOCKER_FILE=$(yq '.components[] | select(.name == "image-build").image.dockerfile.uri' $SAMPLE_DIR/devfile.yaml)
BUILD_CONTEXT=$(yq '.components[] | select(.name == "image-build").image.dockerfile.buildContext' $SAMPLE_DIR/devfile.yaml)
IMAGE_PORT=$(yq '.components[] | select(.name == "kubernetes-deploy").attributes.deployment/container-port' $SAMPLE_DIR/devfile.yaml)

DEST=$ROOT_DIR/templates/$DIRNAME 
rm -rf $DEST
mkdir -p $DEST $DEST/content 
cp -r $SAMPLE_DIR/. $DEST/content  
rm -rf $DEST/content/.git
cp $ROOT_DIR/skeleton/backstage/template.yaml $DEST/template.yaml
cp -r $ROOT_DIR/skeleton/backstage/docs  $DEST/content/docs
cp -r $ROOT_DIR/skeleton/backstage/mkdocs.yml  $DEST/content/mkdocs.yml

# get readme to source component doc
cp -r $DEST/content/README.md  $DEST/content/docs/source-component.md

sed -i "s!sed.edit.NAME!$APP_NAME!g" $DEST/template.yaml
sed -i "s!sed.edit.TITLE!$APP_DISPLAY_NAME!g" $DEST/template.yaml
sed -i "s!sed.edit.DESCRIPTION!$APP_DESC!g" $DEST/template.yaml
sed -i "s!sed.edit.APPTAGS!$APP_TAGS!g" $DEST/template.yaml
sed -i "s!sed.edit.CATALOG_DESCRIPTION!Secure Supply Chain Example for $APP_DESC!g" $DEST/template.yaml
sed -i "s!sed.edit.DOCKERFILE!$DOCKER_FILE!g" $DEST/template.yaml
sed -i "s!sed.edit.BUILDCONTEXT!$BUILD_CONTEXT!g" $DEST/template.yaml
sed -i "s!sed.edit.IMAGEPORT!$IMAGE_PORT!g" $DEST/template.yaml

source $ROOT_DIR/properties
cat $DEST/template.yaml | envsubst > $DEST/new-template.yaml
mv $DEST/new-template.yaml $DEST/template.yaml
