#!/bin/bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" 

$SCRIPTDIR/import-samples https://github.com/redhat-appstudio/devfile-sample-nodejs-dance
$SCRIPTDIR/import-samples https://github.com/redhat-appstudio/devfile-sample-code-with-quarkus-dance 
$SCRIPTDIR/import-samples https://github.com/redhat-appstudio/devfile-sample-java-springboot-dance
$SCRIPTDIR/import-samples https://github.com/redhat-appstudio/devfile-sample-python-dance
$SCRIPTDIR/import-samples https://github.com/redhat-appstudio/devfile-sample-go-dance
$SCRIPTDIR/import-samples https://github.com/redhat-appstudio/devfile-sample-dotnet60-dance

# cleanup cloned path
rm -rf $SCRIPTDIR/samples
