#!/bin/bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" 

$SCRIPTDIR/import-samples https://github.com/redhat-appstudio/ai-sample-chatbot-dance

# cleanup cloned path
rm -rf $SCRIPTDIR/samples
